language: node_js
node_js:
  - '8'
install:
  - yarn install
script:
  - yarn lint
  - yarn flow
  - yarn test
  - yarn build
deploy:
  provider: script
  skip_cleanup: true
  script: yarn deploy
  on:
    branch: master
